config/routes.rb
UWall::Application.routes.draw do
  resources :web_clips
  
  root :to => "web_clips#index"

end

app/models/web_clip.rb
class WebClip < ActiveRecord::Base
  validates :title, :url, :presence => true
  validates :url, :uniqueness => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/web_clips_controller.rb
class WebClipsController < ApplicationController
  # GET /web_clips
  # GET /web_clips.xml
  def index
    @web_clips = WebClip.paginate :page => params[:page], :order => 'created_at desc', :per_page => 10

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @web_clips }
    end
  end

  # GET /web_clips/1
  # GET /web_clips/1.xml
  def show
    @web_clip = WebClip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @web_clip }
    end
  end

  # GET /web_clips/new
  # GET /web_clips/new.xml
  def new
    @web_clip = WebClip.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @web_clip }
    end
  end

  # GET /web_clips/1/edit
  def edit
    @web_clip = WebClip.find(params[:id])
  end

  # POST /web_clips
  # POST /web_clips.xml
  def create
    @web_clip = WebClip.new(params[:web_clip])

    respond_to do |format|
      if @web_clip.save
        format.html { redirect_to(@web_clip, :notice => 'Web clip was successfully created.') }
        format.xml  { render :xml => @web_clip, :status => :created, :location => @web_clip }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @web_clip.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /web_clips/1
  # PUT /web_clips/1.xml
  def update
    @web_clip = WebClip.find(params[:id])

    respond_to do |format|
      if @web_clip.update_attributes(params[:web_clip])
        format.html { redirect_to(@web_clip, :notice => 'Web clip was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @web_clip.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /web_clips/1
  # DELETE /web_clips/1.xml
  def destroy
    @web_clip = WebClip.find(params[:id])
    @web_clip.destroy

    respond_to do |format|
      format.html { redirect_to(web_clips_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/web_clips_helper.rb
module WebClipsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>U-WALL</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/web_clips/_form.html.erb
<%= form_for(@web_clip) do |f| %>
  <% if @web_clip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@web_clip.errors.count, "error") %> prohibited this web_clip from being saved:</h2>

      <ul>
      <% @web_clip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="bookmark">
    <div class="field">
      <%= f.label :url %><br />
      <%= f.text_field :url %>
    </div>
    <div class="field">
      <%= f.label :title %><br />
      <%= f.text_field :title %>
    </div>
    <div class="field">
      <%= f.label :quote %><br />
      <%= f.text_area :quote, :rows => 3 %>
    </div>
    <div class="field">
      <%= f.label :note %><br />
      <%= f.text_area :note, :rows => 3 %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  </div>
<% end %>

app/views/web_clips/edit.html.erb
<h1>Editing Web Clip</h1>

<%= render 'form' %>

<%= link_to 'Show', @web_clip %> |
<%= link_to 'Back', web_clips_path %>

app/views/web_clips/index.html.erb
<strong>Listing Web Clips</strong>

<hr style="border-top:1px dotted #aaa;">

<% @web_clips.each do |web_clip| %>
  <div class="bookmark">
    <%= link_to truncate(web_clip.title, :length =>70), web_clip.url, :target => '_blank', :class => "bookmark_title" %><br />
    <div class="bookmark_quote">
      <%= truncate(web_clip.quote, :length =>80) %><br />
    </div>
    <div class="bookmark_note">
      <%= truncate(web_clip.note, :length =>80) %>
    </div>
    <div class="when">
      <%= time_ago_in_words(web_clip.created_at, true) %>
    </div>
    <div class="edit_links">
      <%= link_to 'Show', web_clip %>
      <%= link_to 'Edit', edit_web_clip_path(web_clip) %>
      <%= link_to 'Destroy', web_clip, :confirm => 'Are you sure?', :method => :delete %>
    </div>
  </div>
<% end %>

<hr style="border-top:1px dotted #aaa;">

<%= link_to 'New Web clip', new_web_clip_path %>
<p><%= will_paginate @web_clip %></p>

app/views/web_clips/new.html.erb
<h1>New Web Clip</h1>

<%= render 'form' %>

<%= link_to 'Back', web_clips_path %>

app/views/web_clips/show.html.erb
<p id="notice"><%= notice %></p>
<div class="bookmark">
  <b>URL:</b>
  <div class="bookmark_title"><%= @web_clip.url %></div>
  <br />
  <b>Title:</b>
  <div class="bookmark_title"><%= @web_clip.title %></div>
  <br />
  <b>Quote:</b>
  <div class="bookmark_quote"><%= @web_clip.quote %></div>
  <br />
  <b>Note:</b>
  <div class="bookmark_note"><%= @web_clip.note %></div>
</div>

<%= link_to 'Edit', edit_web_clip_path(@web_clip) %> |
<%= link_to 'Back', web_clips_path %>